# Datascience Intro

## Numpy
  *Numpy is the fundamental packages for scientific computing*

***Matrix***

*Matrix is a one or multi dimensional array*

*One Dimensional matrix/array*

$$\begin{bmatrix} 1 & 2 & 1 \end{bmatrix}$$ 
***rank: 1x3***
$$\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$$
***rank: 3x1***

*Two Dimensional matrix/array*

$$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$
***rank: 3x3***

$$\begin{bmatrix} 1 & 2 \\ 3 & 0 \\ 0 & 2 \end{bmatrix}$$
***rank:3x2***

### Position of element in a array

***Position of element in the matrix or array***

$$\begin{bmatrix} 8 & 2 \\ 9 & 4 \\ 3 & 7 \end{bmatrix}$$

***Find the position of 4: row:1, col:1 (1, 1)***

------------

$$\begin{bmatrix} 1 & 6 & 9 \\ 16 & 42 & 53 \\ 7 & 5 & 12 \end{bmatrix}$$


In [2]:
import numpy as np

In [5]:
a = np.arange(1,7)

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a.shape

(6,)

In [8]:
a.ndim

1

In [15]:
b = a.reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
b.shape

(3, 2)

In [18]:
b.ndim

2

In [16]:
c = a.reshape(2, 3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
c.shape

(2, 3)

In [19]:
c.ndim

2

In [20]:
d = a.reshape(1, 6)
d

array([[1, 2, 3, 4, 5, 6]])

In [21]:
d.shape

(1, 6)

In [23]:
d.ndim

2

In [30]:
a.dtype

dtype('int32')

In [26]:
a.astype('int8')

array([1, 2, 3, 4, 5, 6], dtype=int8)

* int8 - *TinyInt*
* int16 - *SmallInt*
* int32 - *MediumInt*
* int64 - *BigInt*

In [29]:
# Number of elements
a.size

6

#### **Create a array in numpy**

In [36]:
new_array = np.array([[1], [2], [3]])
new_array

array([[1],
       [2],
       [3]])

In [35]:
new_2d_array = np.array([[1, 3], [2, 5], [3, 7]])
new_2d_array

array([[1, 3],
       [2, 5],
       [3, 7]])

In [44]:
new_2d_array[2][1]

7

In [45]:
# matrrix 1
np.arange(1,24,3).reshape(2,4)

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

In [47]:
# matrix 2
np.arange(4,20,2).reshape(4,2)

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [51]:
# matrix 3
np.arange(1, 100, 5).reshape(5,4)

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])