# Datascience Intro

## Numpy
  *Numpy is the fundamental packages for scientific computing*

***Matrix***

*Matrix is a one or multi dimensional array*

*One Dimensional matrix/array*

$$\begin{bmatrix} 1 & 2 & 1 \end{bmatrix}$$ 
***rank: 1x3***
$$\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$$
***rank: 3x1***

*Two Dimensional matrix/array*

$$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$
***rank: 3x3***

$$\begin{bmatrix} 1 & 2 \\ 3 & 0 \\ 0 & 2 \end{bmatrix}$$
***rank:3x2***

### Position of element in a array

***Position of element in the matrix or array***

$$\begin{bmatrix} 8 & 2 \\ 9 & 4 \\ 3 & 7 \end{bmatrix}$$

***Find the position of 4: row:1, col:1 (1, 1)***

------------

$$\begin{bmatrix} 1 & 6 & 9 \\ 16 & 42 & 53 \\ 7 & 5 & 12 \end{bmatrix}$$


In [2]:
import numpy as np

In [5]:
a = np.arange(1,7)

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a.shape

(6,)

In [8]:
a.ndim

1

In [15]:
b = a.reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
b.shape

(3, 2)

In [18]:
b.ndim

2

In [16]:
c = a.reshape(2, 3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
c.shape

(2, 3)

In [19]:
c.ndim

2

In [20]:
d = a.reshape(1, 6)
d

array([[1, 2, 3, 4, 5, 6]])

In [21]:
d.shape

(1, 6)

In [23]:
d.ndim

2

In [30]:
a.dtype

dtype('int32')

In [26]:
a.astype('int8')

array([1, 2, 3, 4, 5, 6], dtype=int8)

* int8 - *TinyInt*
* int16 - *SmallInt*
* int32 - *MediumInt*
* int64 - *BigInt*

In [29]:
# Number of elements
a.size

6

#### **Create a array in numpy**

In [36]:
new_array = np.array([[1], [2], [3]])
new_array

array([[1],
       [2],
       [3]])

In [35]:
new_2d_array = np.array([[1, 3], [2, 5], [3, 7]])
new_2d_array

array([[1, 3],
       [2, 5],
       [3, 7]])

In [44]:
new_2d_array[2][1]

7

In [45]:
# matrrix 1
np.arange(1,24,3).reshape(2,4)

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

In [47]:
# matrix 2
np.arange(4,20,2).reshape(4,2)

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [51]:
# matrix 3
np.arange(1, 100, 5).reshape(5,4)

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

#### Creating empty, ones and zeros numpy array

In [7]:
ones_array = np.ones((6, 4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
zeros_array = np.zeros((5, 8))
zeros_array

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
empty_array = np.empty((2, 3))
empty_array

array([[1., 1., 1.],
       [1., 1., 1.]])

#### slicing in numpy array

In [23]:
simple_array = np.arange(0, 24, 2).reshape(4, 3)
simple_array

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [34]:
simple_array[2:, 1:]

array([[14, 16],
       [20, 22]])

In [40]:
sec_simple_array = np.arange(3, 57, 3).reshape(6, 3)
sec_simple_array

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36],
       [39, 42, 45],
       [48, 51, 54]])

In [41]:
empty_list = [1, 3, 5, 7, 9]
empty_list[1:4]

[3, 5, 7]

In [42]:
simple_array

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [48]:
simple_array[1:3, 0:2]

array([[ 6,  8],
       [12, 14]])

#### Stacking numpy arrays

In [58]:
a = np.arange(1, 5).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

In [55]:
b = np.arange(2, 10, 2).reshape(2, 2)
b

array([[2, 4],
       [6, 8]])

In [62]:
c = np.vstack((a, b))
c

array([[1, 2],
       [3, 4],
       [2, 4],
       [6, 8]])

#### Flatten the numpy arrays

In [78]:
a = np.arange(9, 81, 9).reshape(4, 2)
a

array([[ 9, 18],
       [27, 36],
       [45, 54],
       [63, 72]])

In [70]:
a.ravel()

array([ 9, 18, 27, 36, 45, 54, 63, 72])

In [71]:
a.reshape((8,))

array([ 9, 18, 27, 36, 45, 54, 63, 72])

In [74]:
a.flatten()

array([ 9, 18, 27, 36, 45, 54, 63, 72])

#### Splitting a numpy array

In [79]:
split_array = np.arange(3, 57, 3).reshape(6, 3)
split_array

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36],
       [39, 42, 45],
       [48, 51, 54]])

In [80]:
np.vsplit(split_array, 3)

[array([[ 3,  6,  9],
        [12, 15, 18]]),
 array([[21, 24, 27],
        [30, 33, 36]]),
 array([[39, 42, 45],
        [48, 51, 54]])]

In [81]:
np.hsplit(split_array, 3)

[array([[ 3],
        [12],
        [21],
        [30],
        [39],
        [48]]),
 array([[ 6],
        [15],
        [24],
        [33],
        [42],
        [51]]),
 array([[ 9],
        [18],
        [27],
        [36],
        [45],
        [54]])]

*`Notes`*: ***Referencing the same array with new variable modify original array***

In [92]:
a = np.arange(1, 5).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

In [93]:
b = a
b

array([[1, 2],
       [3, 4]])

In [94]:
b[1][1] = 8
b

array([[1, 2],
       [3, 8]])

In [95]:
a

array([[1, 2],
       [3, 8]])

In [96]:
c = a.copy()
c

array([[1, 2],
       [3, 8]])

In [97]:
c[1][1] = 9

In [98]:
c

array([[1, 2],
       [3, 9]])

In [99]:
a

array([[1, 2],
       [3, 8]])

#### Array indexing with the conditions

In [104]:
new_array = np.arange(5, 65, 5).reshape(4, 3)
new_array

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [109]:
new_array[new_array <= 25]

array([ 5, 10, 15, 20, 25])

#### Performing mathematical operations on numpy array

***Assignment 1***

*write a short para about mean, median, mode and standard deviation ?*

### Intro to 3D array

#### visualizing the 3D array

#### indexing and slicing the 3d array

#### applying basic numpy functions 3d array