# Datascience Intro

## Numpy
  *Numpy is the fundamental packages for scientific computing*

***Matrix***

*Matrix is a one or multi dimensional array*

*One Dimensional matrix/array*

$$\begin{bmatrix} 1 & 2 & 1 \end{bmatrix}$$ 
***rank: 1x3***
$$\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$$
***rank: 3x1***

*Two Dimensional matrix/array*

$$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$
***rank: 3x3***

$$\begin{bmatrix} 1 & 2 \\ 3 & 0 \\ 0 & 2 \end{bmatrix}$$
***rank:3x2***

### Position of element in a array

***Position of element in the matrix or array***

$$\begin{bmatrix} 8 & 2 \\ 9 & 4 \\ 3 & 7 \end{bmatrix}$$

***Find the position of 4: row:1, col:1 (1, 1)***

------------

$$\begin{bmatrix} 1 & 6 & 9 \\ 16 & 42 & 53 \\ 7 & 5 & 12 \end{bmatrix}$$


In [1]:
import numpy as np

In [5]:
a = np.arange(1,7)

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a.shape

(6,)

In [8]:
a.ndim

1

In [15]:
b = a.reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
b.shape

(3, 2)

In [18]:
b.ndim

2

In [16]:
c = a.reshape(2, 3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
c.shape

(2, 3)

In [19]:
c.ndim

2

In [20]:
d = a.reshape(1, 6)
d

array([[1, 2, 3, 4, 5, 6]])

In [21]:
d.shape

(1, 6)

In [23]:
d.ndim

2

In [30]:
a.dtype

dtype('int32')

In [26]:
a.astype('int8')

array([1, 2, 3, 4, 5, 6], dtype=int8)

* int8 - *TinyInt*
* int16 - *SmallInt*
* int32 - *MediumInt*
* int64 - *BigInt*

In [29]:
# Number of elements
a.size

6

#### **Create a array in numpy**

In [36]:
new_array = np.array([[1], [2], [3]])
new_array

array([[1],
       [2],
       [3]])

In [35]:
new_2d_array = np.array([[1, 3], [2, 5], [3, 7]])
new_2d_array

array([[1, 3],
       [2, 5],
       [3, 7]])

In [44]:
new_2d_array[2][1]

7

In [45]:
# matrrix 1
np.arange(1,24,3).reshape(2,4)

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

In [47]:
# matrix 2
np.arange(4,20,2).reshape(4,2)

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [51]:
# matrix 3
np.arange(1, 100, 5).reshape(5,4)

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

#### Creating empty, ones and zeros numpy array

In [7]:
ones_array = np.ones((6, 4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
zeros_array = np.zeros((5, 8))
zeros_array

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
empty_array = np.empty((2, 3))
empty_array

array([[1., 1., 1.],
       [1., 1., 1.]])

#### slicing in numpy array

In [23]:
simple_array = np.arange(0, 24, 2).reshape(4, 3)
simple_array

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [34]:
simple_array[2:, 1:]

array([[14, 16],
       [20, 22]])

In [40]:
sec_simple_array = np.arange(3, 57, 3).reshape(6, 3)
sec_simple_array

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36],
       [39, 42, 45],
       [48, 51, 54]])

In [41]:
empty_list = [1, 3, 5, 7, 9]
empty_list[1:4]

[3, 5, 7]

In [42]:
simple_array

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [48]:
simple_array[1:3, 0:2]

array([[ 6,  8],
       [12, 14]])

#### Stacking numpy arrays

In [58]:
a = np.arange(1, 5).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

In [55]:
b = np.arange(2, 10, 2).reshape(2, 2)
b

array([[2, 4],
       [6, 8]])

In [62]:
c = np.vstack((a, b))
c

array([[1, 2],
       [3, 4],
       [2, 4],
       [6, 8]])

#### Flatten the numpy arrays

In [78]:
a = np.arange(9, 81, 9).reshape(4, 2)
a

array([[ 9, 18],
       [27, 36],
       [45, 54],
       [63, 72]])

In [70]:
a.ravel()

array([ 9, 18, 27, 36, 45, 54, 63, 72])

In [71]:
a.reshape((8,))

array([ 9, 18, 27, 36, 45, 54, 63, 72])

In [74]:
a.flatten()

array([ 9, 18, 27, 36, 45, 54, 63, 72])

#### Splitting a numpy array

In [79]:
split_array = np.arange(3, 57, 3).reshape(6, 3)
split_array

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36],
       [39, 42, 45],
       [48, 51, 54]])

In [80]:
np.vsplit(split_array, 3)

[array([[ 3,  6,  9],
        [12, 15, 18]]),
 array([[21, 24, 27],
        [30, 33, 36]]),
 array([[39, 42, 45],
        [48, 51, 54]])]

In [81]:
np.hsplit(split_array, 3)

[array([[ 3],
        [12],
        [21],
        [30],
        [39],
        [48]]),
 array([[ 6],
        [15],
        [24],
        [33],
        [42],
        [51]]),
 array([[ 9],
        [18],
        [27],
        [36],
        [45],
        [54]])]

*`Notes`*: ***Referencing the same array with new variable modify original array***

In [92]:
a = np.arange(1, 5).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

In [93]:
b = a
b

array([[1, 2],
       [3, 4]])

In [94]:
b[1][1] = 8
b

array([[1, 2],
       [3, 8]])

In [95]:
a

array([[1, 2],
       [3, 8]])

In [96]:
c = a.copy()
c

array([[1, 2],
       [3, 8]])

In [97]:
c[1][1] = 9

In [98]:
c

array([[1, 2],
       [3, 9]])

In [99]:
a

array([[1, 2],
       [3, 8]])

#### Array indexing with the conditions

In [104]:
new_array = np.arange(5, 65, 5).reshape(4, 3)
new_array

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [109]:
new_array[new_array <= 25]

array([ 5, 10, 15, 20, 25])

#### Performing mathematical operations on numpy array

In [2]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6], [7, 8]])

print("a", a.shape, "\nb", b.shape)

a (2, 2) 
b (2, 2)


#### Adding the two Matrices

In [3]:
a + b

array([[ 6,  8],
       [10, 12]])

In [5]:
a

array([[1, 2],
       [3, 4]])

#### Broadcasting

In [4]:
a + 12

array([[13, 14],
       [15, 16]])

In [12]:
c = np.arange(1, 10).reshape((3, 3))
print(c, c.shape, c.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 9


In [15]:
print(a)
print("") 
print(c)

[[1 2]
 [3 4]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
a + [1, 2]

array([[2, 4],
       [4, 6]])

In [20]:
print(a, "\n\n", b)

[[1 2]
 [3 4]] 

 [[5 6]
 [7 8]]


#### Same applies for Subtraction

In [17]:
a - b

array([[-4, -4],
       [-4, -4]])

#### Multiplication on 2d matrices

In [42]:
np.random.seed(42)
a = np.array([[1, 2], [3, 4]])
b = np.random.random(size=(2, 2))*10
b = b.astype("int16")

print(a, "\n\n", b)

[[1 2]
 [3 4]] 

 [[3 9]
 [7 5]]


In [44]:
a.dot(b)

array([[17, 19],
       [37, 47]])

In [45]:
print(a.shape, b.shape)

(2, 2) (2, 2)


In [49]:
a = np.array([[1, 2, 1], [3, 4, 5]])
b = np.random.random(size=(2, 3))*10
b = b.astype("int16")

print(a, "\n\n", b, "\n")
print(a.shape,b.shape)


[[1 2 1]
 [3 4 5]] 

 [[3 5 4]
 [2 6 1]] 

(2, 3) (2, 3)


In [52]:
b = b.reshape((3, 2))

print(a.shape,b.shape)

print(b)

(2, 3) (3, 2)
[[3 5]
 [4 2]
 [6 1]]


In [51]:
a.dot(b)

array([[17, 10],
       [55, 28]])

<a href="http://matrixmultiplication.xyz/">matrix multiplication link</a>

In [56]:
np.random.seed(42)
a = np.random.random((3, 2))*10
a = a.astype("int16")
np.random.seed(32)
b = np.random.random((3, 2))*10
b = b.astype("int16")

print(a, "\n\n", b)


[[3 9]
 [7 5]
 [1 1]] 

 [[8 3]
 [5 9]
 [7 8]]


***Assignment 1***

*write a short para about mean, median, mode and standard deviation ?*

### Intro to 3D array

#### visualizing the 3D array

In [2]:
simple_3d_array = np.random.random_integers(1, 10, size=(2, 3, 2))

simple_3d_array

C:\Users\Navazdeen S\AppData\Local\Temp\ipykernel_23104\3116609706.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  simple_3d_array = np.random.random_integers(1, 10, size=(2, 3, 2))


array([[[10, 10],
        [ 3, 10],
        [ 2,  1]],

       [[ 5, 10],
        [ 1,  9],
        [ 3,  1]]])

In [3]:
simple_3d_array.shape

(2, 3, 2)

#### indexing and slicing the 3d array

In [4]:
multi_dim_array = np.random.randint(1, 5, size=(2, 3, 2, 2))
multi_dim_array

array([[[[4, 4],
         [3, 3]],

        [[3, 2],
         [4, 4]],

        [[2, 4],
         [3, 4]]],


       [[[2, 4],
         [2, 3]],

        [[4, 4],
         [2, 1]],

        [[1, 4],
         [4, 3]]]])

In [5]:
simple_3d_array

array([[[10, 10],
        [ 3, 10],
        [ 2,  1]],

       [[ 5, 10],
        [ 1,  9],
        [ 3,  1]]])

In [66]:
simple_3d_array[0, 1, 1]

10

In [8]:
flatten_array = simple_3d_array.flatten()
flatten_array

array([10, 10,  3, 10,  2,  1,  5, 10,  1,  9,  3,  1])

In [71]:
flatten_array.sum()

73

***Mean : sum(total elements)/number of elements***

In [73]:
mean = flatten_array.sum()/flatten_array.size

mean

6.083333333333333

In [74]:
simple_3d_array.mean()

6.083333333333333

***Mode, median, std_dev, variance***

#### applying basic numpy functions 3d array

In [6]:
simple_3d_array

array([[[10, 10],
        [ 3, 10],
        [ 2,  1]],

       [[ 5, 10],
        [ 1,  9],
        [ 3,  1]]])

In [16]:
sorted_flatten = np.sort(flatten_array)
sorted_flatten

array([ 1,  1,  1,  2,  3,  3,  5,  9, 10, 10, 10, 10])

In [18]:
sorted_flatten.size

12

In [20]:
(sorted_flatten[5] + sorted_flatten[6])/2

4.0

In [21]:
np.median(flatten_array)

4.0

In [29]:
sorted_flatten[9] = 1
sorted_flatten

array([ 1,  1,  1,  2,  3,  3,  5,  9, 10,  1, 10, 10])

In [30]:
lst  = list(sorted_flatten)
max_count =0
mode = 0
for element in set(sorted_flatten):
    if max_count < lst.count(element):
        max_count = lst.count(element)
        mode = element
print(mode)

1


In [33]:
from statistics import mode

mode(sorted_flatten)

1

In [37]:
std_dev = np.sqrt(np.sum((sorted_flatten - sorted_flatten.mean())**2)/sorted_flatten.size)
std_dev

3.7712361663282534

In [36]:
sorted_flatten.std()

3.7712361663282534

In [38]:
var = np.sum((sorted_flatten - sorted_flatten.mean())**2)/sorted_flatten.size
var

14.222222222222223

In [39]:
sorted_flatten.var()

14.222222222222223

In [46]:
np.linspace(1, 10, 12)

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="381px" viewBox="-0.5 -0.5 381 89" content="&lt;mxfile&gt;&lt;diagram id=&quot;2k-d82Y6qp13Swk0z7LV&quot; name=&quot;Page-1&quot;&gt;&lt;mxGraphModel dx=&quot;764&quot; dy=&quot;644&quot; grid=&quot;1&quot; gridSize=&quot;10&quot; guides=&quot;1&quot; tooltips=&quot;1&quot; connect=&quot;1&quot; arrows=&quot;1&quot; fold=&quot;1&quot; page=&quot;1&quot; pageScale=&quot;1&quot; pageWidth=&quot;850&quot; pageHeight=&quot;1100&quot; background=&quot;#ffffff&quot; math=&quot;0&quot; shadow=&quot;0&quot;&gt;&lt;root&gt;&lt;mxCell id=&quot;0&quot;/&gt;&lt;mxCell id=&quot;1&quot; parent=&quot;0&quot;/&gt;&lt;mxCell id=&quot;2&quot; value=&quot;&quot; style=&quot;endArrow=none;html=1;strokeColor=#000000;&quot; parent=&quot;1&quot; edge=&quot;1&quot;&gt;&lt;mxGeometry width=&quot;50&quot; height=&quot;50&quot; relative=&quot;1&quot; as=&quot;geometry&quot;&gt;&lt;mxPoint x=&quot;200&quot; y=&quot;270&quot; as=&quot;sourcePoint&quot;/&gt;&lt;mxPoint x=&quot;520&quot; y=&quot;270&quot; as=&quot;targetPoint&quot;/&gt;&lt;/mxGeometry&gt;&lt;/mxCell&gt;&lt;mxCell id=&quot;3&quot; value=&quot;0&quot; style=&quot;text;html=1;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fillColor=#d0cee2;strokeColor=#56517e;&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;&lt;mxGeometry x=&quot;170&quot; y=&quot;280&quot; width=&quot;60&quot; height=&quot;30&quot; as=&quot;geometry&quot;/&gt;&lt;/mxCell&gt;&lt;mxCell id=&quot;4&quot; value=&quot;20&quot; style=&quot;text;html=1;strokeColor=#56517e;fillColor=#d0cee2;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;&lt;mxGeometry x=&quot;490&quot; y=&quot;280&quot; width=&quot;60&quot; height=&quot;30&quot; as=&quot;geometry&quot;/&gt;&lt;/mxCell&gt;&lt;mxCell id=&quot;5&quot; value=&quot;10&quot; style=&quot;text;html=1;strokeColor=#56517e;fillColor=#d0cee2;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;&quot; parent=&quot;1&quot; vertex=&quot;1&quot;&gt;&lt;mxGeometry x=&quot;330&quot; y=&quot;280&quot; width=&quot;60&quot; height=&quot;30&quot; as=&quot;geometry&quot;/&gt;&lt;/mxCell&gt;&lt;mxCell id=&quot;6&quot; value=&quot;&quot; style=&quot;endArrow=classic;startArrow=classic;html=1;strokeColor=#0A0A0A;&quot; parent=&quot;1&quot; edge=&quot;1&quot;&gt;&lt;mxGeometry width=&quot;50&quot; height=&quot;50&quot; relative=&quot;1&quot; as=&quot;geometry&quot;&gt;&lt;mxPoint x=&quot;200&quot; y=&quot;250&quot; as=&quot;sourcePoint&quot;/&gt;&lt;mxPoint x=&quot;360&quot; y=&quot;250&quot; as=&quot;targetPoint&quot;/&gt;&lt;/mxGeometry&gt;&lt;/mxCell&gt;&lt;mxCell id=&quot;7&quot; value=&quot;&quot; style=&quot;endArrow=classic;startArrow=classic;html=1;strokeColor=#000000;&quot; parent=&quot;1&quot; edge=&quot;1&quot;&gt;&lt;mxGeometry width=&quot;50&quot; height=&quot;50&quot; relative=&quot;1&quot; as=&quot;geometry&quot;&gt;&lt;mxPoint x=&quot;200&quot; y=&quot;230&quot; as=&quot;sourcePoint&quot;/&gt;&lt;mxPoint x=&quot;520&quot; y=&quot;230&quot; as=&quot;targetPoint&quot;/&gt;&lt;/mxGeometry&gt;&lt;/mxCell&gt;&lt;/root&gt;&lt;/mxGraphModel&gt;&lt;/diagram&gt;&lt;/mxfile&gt;" onclick="(function(svg){var src=window.event.target||window.event.srcElement;while (src!=null&amp;&amp;src.nodeName.toLowerCase()!='a'){src=src.parentNode;}if(src==null){if(svg.wnd!=null&amp;&amp;!svg.wnd.closed){svg.wnd.focus();}else{var r=function(evt){if(evt.data=='ready'&amp;&amp;evt.source==svg.wnd){svg.wnd.postMessage(decodeURIComponent(svg.getAttribute('content')),'*');window.removeEventListener('message',r);}};window.addEventListener('message',r);svg.wnd=window.open('https://viewer.diagrams.net/?client=1&amp;page=0&amp;edit=_blank');}}})(this);" style="cursor:pointer;max-width:100%;max-height:89px;"><defs/><g><path d="M 30 48 L 350 48" fill="none" stroke="#000000" stroke-miterlimit="10" pointer-events="stroke"/><rect x="0" y="58" width="60" height="30" fill="#d0cee2" stroke="#56517e" pointer-events="all"/><g transform="translate(-0.5 -0.5)"><switch><foreignObject pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility" style="overflow: visible; text-align: left;"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 58px; height: 1px; padding-top: 73px; margin-left: 1px;"><div data-drawio-colors="color: rgb(0, 0, 0); " style="box-sizing: border-box; font-size: 0px; text-align: center;"><div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: rgb(0, 0, 0); line-height: 1.2; pointer-events: all; white-space: normal; overflow-wrap: normal;">0</div></div></div></foreignObject><text x="30" y="77" fill="rgb(0, 0, 0)" font-family="Helvetica" font-size="12px" text-anchor="middle">0</text></switch></g><rect x="320" y="58" width="60" height="30" fill="#d0cee2" stroke="#56517e" pointer-events="all"/><g transform="translate(-0.5 -0.5)"><switch><foreignObject pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility" style="overflow: visible; text-align: left;"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 58px; height: 1px; padding-top: 73px; margin-left: 321px;"><div data-drawio-colors="color: rgb(0, 0, 0); " style="box-sizing: border-box; font-size: 0px; text-align: center;"><div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: rgb(0, 0, 0); line-height: 1.2; pointer-events: all; white-space: normal; overflow-wrap: normal;">20</div></div></div></foreignObject><text x="350" y="77" fill="rgb(0, 0, 0)" font-family="Helvetica" font-size="12px" text-anchor="middle">20</text></switch></g><rect x="160" y="58" width="60" height="30" fill="#d0cee2" stroke="#56517e" pointer-events="all"/><g transform="translate(-0.5 -0.5)"><switch><foreignObject pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility" style="overflow: visible; text-align: left;"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 58px; height: 1px; padding-top: 73px; margin-left: 161px;"><div data-drawio-colors="color: rgb(0, 0, 0); " style="box-sizing: border-box; font-size: 0px; text-align: center;"><div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: rgb(0, 0, 0); line-height: 1.2; pointer-events: all; white-space: normal; overflow-wrap: normal;">10</div></div></div></foreignObject><text x="190" y="77" fill="rgb(0, 0, 0)" font-family="Helvetica" font-size="12px" text-anchor="middle">10</text></switch></g><path d="M 36.37 28 L 183.63 28" fill="none" stroke="#0a0a0a" stroke-miterlimit="10" pointer-events="stroke"/><path d="M 31.12 28 L 38.12 24.5 L 36.37 28 L 38.12 31.5 Z" fill="#0a0a0a" stroke="#0a0a0a" stroke-miterlimit="10" pointer-events="all"/><path d="M 188.88 28 L 181.88 31.5 L 183.63 28 L 181.88 24.5 Z" fill="#0a0a0a" stroke="#0a0a0a" stroke-miterlimit="10" pointer-events="all"/><path d="M 36.37 8 L 343.63 8" fill="none" stroke="#000000" stroke-miterlimit="10" pointer-events="stroke"/><path d="M 31.12 8 L 38.12 4.5 L 36.37 8 L 38.12 11.5 Z" fill="#000000" stroke="#000000" stroke-miterlimit="10" pointer-events="all"/><path d="M 348.88 8 L 341.88 11.5 L 343.63 8 L 341.88 4.5 Z" fill="#000000" stroke="#000000" stroke-miterlimit="10" pointer-events="all"/></g><switch><g requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"/><a transform="translate(0,-5)" xlink:href="https://www.diagrams.net/doc/faq/svg-export-text-problems" target="_blank"><text text-anchor="middle" font-size="10px" x="50%" y="100%">Viewer does not support full SVG 1.1</text></a></switch></svg>